#!/bin/bash
#
#FILE ADD
echo -n "Faili location ~/github/"
read fileLoc
if [ $fileLoc -ne "-" ]; then
	git add ~/github/$fileLoc
else
	echo "Addisid ise failid: OK"
fi

#GIT COMMIT
echo -n "Selgitus mis tegid: "
read selgitus
git commit -m \"$selgitus\"
echo "Olete ise addinud faili: OK"

#GIT PUSH
echo -n "Mis repository'sse see läheb? "
read repo
git push -u $repo master

