#!/bin/bash
#
if [ $# -ne 1 ]; then
	echo " "
	echo " "
	echo " "
	echo "KASUTUSJUHEND: "
	echo "Palun sisesta 1 number peale \""$0"\""
	echo "Näiteks:" $0 "5"
else
	if [ $1 -gt 1 ]; then
			echo $1 "On positiivne arv."
		elif [ $1 -eq 0 ]; then
			echo $1 "On neutraalne arv."
		else
			echo $1 "On negatiivne arv."
	fi
fi
